### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by helfer**
* Update and add more rows in comparison table

### CODE REVIEW

**Comment by mattkrick** [comment]
Well done on the subs!

**Comment by jordanh** [comment]
Bravo!

**Comment by mattkrick** [comment]
@helfer merged too soon... the full GraphQL spec supports List of Lists, multiple operations inside of mutations, and multiple operations inside of subscriptions. Apollo doesn't.

**Comment by helfer** [comment]
@mattkrick Haha, true! Although nobody has defined what that actually means. Do you then get the full selection set any time one of the subscriptions was updated? We should all sit together some time an hash out the subscription spec among all the people that have implemented something now.

**Comment by mattkrick** [comment]
@helfer 
Agreed! I think the things that we don't support shouldn't be supported. 

- Currently, the GraphQL spec supports Lists of Lists of Lists of..... which is just crazy. I'd like them to take an opinionated stand & say a list of a list is an antipattern & just not support it. Or _maybe_ go 1 level deep as a compromise, although no client cache supports that.
- For multiple operations in a mutation, again, I think it's an antipattern & no client lib supports it & I've never come across a use case for it.
- For multiple operations in a sub, again, i don't think it should exist. If it does exist, we'd have to use falcor-like paths, which I supported in a previous version, but I didn't like since it gets complicated to do that on the server & requires a `path` stack to be in the outer-most closure & then we'd have to write that `path` part in the GraphQL spec & it just gets hairy.

Also, Cashay supports GraphQL directives (as well as its own) now. And Relay works without sending the GraphQL client schema to the client, so I reverted those, since the latter was already taken care of by the client-schema line above. Lemme know if that works for you!

**Comment by helfer** [comment]
Yeah, I actually think we should take up that discussion on the graphql repo or something.

Also, I just realized that I agreed too soon earlier. Subscriptions aren't part of the spec yet, so Apollo **does** support the full spec ;)

**Comment by mattkrick** [comment]
only as much as cashay & relay do :smile:

**Pull request merged**
