### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by helfer**
Clarify that Apollo supports all features of the [official spec](https://facebook.github.io/graphql/) since subscriptions are not yet part of it.

### CODE REVIEW

**Comment by helfer** [comment]
Sorry, I just couldn't stop myself from doing it! 😁

**Comment by mattkrick** [comment]
Mmmm, 4.2.2.9?

**Comment by helfer** [comment]
Yeah, afaik apollo supports arbitrary nesting of lists and non-nulls, even more than 7 levels, which is the limit for GraphiQL.

**Comment by mattkrick** [comment]
2.4 as it relates to 2.3. You support multiple mutations under the same mutation operation?

**Comment by helfer** [comment]
Yeah, we do.

**Comment by mattkrick** [comment]
That's amazing! You gotta brag about that in your docs
Seeing the `submitRepository` mutation  and the operation `submitRepository` make it appear that  a mutation can only have 1 child. :wink:

**Pull request merged**
